name: "Synchronise Coverity Scan branches on a weekly basis"

on:
  workflow_dispatch:
  schedule:
    - cron: "7 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git diff --exit-code -s origin/coverity-fixes origin/fixes
          if [ "$?" = "1" ]; then
            git checkout -b coverity-fixes origin/fixes
            git push origin coverity-fixes
          fi
          git diff --exit-code -s origin/coverity-develop origin/develop
          if [ "$?" = "1" ]; then
            git checkout -b coverity-develop origin/develop
            git push origin coverity-develop
          fi
